name: Deploy

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger deployment on Render
        run: curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK }}
